project/home/views.py
__author__ = 'Peter'

from project.models import * # pragma: no cover
from flask import render_template,Blueprint,flash,redirect,url_for,request,session # pragma: no cover
from flask_wtf import Form  # pragma: no cover
from wtforms import RadioField,HiddenField  # pragma: no cover
from wtforms.validators import DataRequired  # pragma: no cover
from flask.ext.login import login_required # pragma: no cover
from project.home.form import AddSeriesForm, EditSeriesForm # pragma: no cover
from project import db # pragma: no cover
import json, requests
from html.parser import HTMLParser



##########
# Config #
##########

home_blueprint = Blueprint(
    'home', __name__,
    template_folder='templates'
) # pragma: no cover

##########
# Routes #
##########

@home_blueprint.route('/')
@login_required
def home():
    shows = db.session.query(Show).order_by(Show.title).all()
    files = db.session.query(Download).all()
    return render_template('index.html', shows=shows, downloads=files)

@home_blueprint.route('/welcome')
def welcome():
    return render_template('welcome.html')

@home_blueprint.route('/show/<title>', methods=['GET','POST'])
@login_required
def show(show):
    current_show = Show.query.filter_by(title=show).first()
    pass


@home_blueprint.route('/add', methods=['GET','POST'])
@login_required
def add():
    form = AddSeriesForm(request.form)
    if form.validate_on_submit():
        session['title'] = form.title.data
        session['watching'] = form.watching.data
        session['finished'] = form.finished.data

        return redirect(url_for('home.set_tvmaze_id'))
    return render_template('add.html', form=form)

@login_required
@home_blueprint.route('/set_tvmaze_id', methods=['GET', 'POST'])
def set_tvmaze_id():

    class F(Form):
        pass

    class MLStripper(HTMLParser):
        def __init__(self):
            super(MLStripper,self).__init__()
            self.reset()
            self.fed = []
        def handle_data(self, d):
            self.fed.append(d)
        def get_data(self):
            return ''.join(self.fed)

    def strip_tags(html):
        s = MLStripper()
        s.feed(html)
        return s.get_data()

    response=requests.get("http://api.tvmaze.com/search/shows?q="+session['title'])
    print(response)
    json_data=json.loads(response.text)
    options = []

    #
    # TODO: Add check for certain json parts not existing
    #

    for item in json_data:
        options.append(
            (
                str(item['show']['id']),
                item['show']['name'],
                (
                    item['show']['network']['name'] if item['show']['network'] else item['show']['webChannel']['name'],
                    strip_tags(item['show']['summary']),
                    item['show']['image']['medium'])
            )
        )




    class FancyRadioField(RadioField):
        def __init__(self, **kwds):
            super(FancyRadioField,self).__init__(**kwds)

        def iter_choices(self):
            for value, label, extra_data in self.choices:
                yield (value, label, extra_data, self.coerce(value) == self.data)

        def __iter__(self):
            opts = dict(widget=self.option_widget, _name=self.name, _form=None, _meta=self.meta)
            for i, (value, label,extra_data, checked) in enumerate(self.iter_choices()):
                opt = self._Option(label=label, id='%s-%d' % (self.id, i), **opts)
                opt.process(None, value)
                opt.checked = checked
                opt.extra_data=extra_data
                yield opt

        def validate(self, form, extra_validators=tuple()):
            print('validating')
            return super(FancyRadioField,self).validate(form, extra_validators)
            print('done validating')

        def pre_validate(self, form):
            for v, _, extra_data in self.choices:
                if self.data == v:
                    print("valid choice:" + str(self.data))
                    break
            else:
                raise ValueError(self.gettext('Not a valid choice'))


    F.selection = FancyRadioField(
        label='selection',
        choices=options,
        validators=[DataRequired()]
       )

    F.title = HiddenField(
        label='title'
    )


    form = F(request.form)

    #
    # TODO: Add a check to see if this series is already in the DB
    #

    #print(options)

    if form.validate_on_submit():
        print("In the if statement")
        print(form.data.items())
        show = Show(
            title=form.title.data,
            watching=session['watching'],
            finished=session['finished'],
            tvmaze_id = form.selection.data
        )
        test = db.session.query(Show).filter(Show.title == show.title).first()
        print("Show title: " + show.title)
        print(test)
        db.session.add(show)
        db.session.commit()
        return redirect(url_for('home.home'))
    return render_template('set_tvmaze_id.html', form=form)


@home_blueprint.route('/edit/<show>', methods=['GET','POST'])
@login_required
def edit(show):
    form = EditSeriesForm(request.form)
    show_to_edit = Show.query.filter_by(title=show).first()

    if form.validate_on_submit():
        if request.form['btn'] == 'save':
            show_to_edit.watching = form.watching.data
            db.session.commit()
            flash("Successfully edited!")
            return redirect(url_for('home.home'))
        else:
            return redirect(url_for('home.home'))
    form.watching.data = show_to_edit.watching
    form.finished.data = show_to_edit.finished
    return render_template('edit.html', form=form, show=show)

project/home/templates/add.html
{% extends "base.html" %}

{% block content %}

<h1>Add series</h1>
<br>
<form class="form-signin" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
    {{ form.title(placeholder="title") }}
    <span class="error">
      {% if form.title.errors %}
        {% for error in form.title.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
      {{ form.watching(class_="checkbox-inline",checked="checked") }} Watching
  </p>
  <p>
      {{ form.finished(class_="checkbox-inline") }} Finished
  </p>

  <button class="btn btn-sm btn-success" type="submit">Add!</button>
</form>

{% endblock %}

project/home/templates/edit.html
{% extends "base.html" %}

{% block content %}

<h1>Edit series</h1>
<br>
<form class="form-signin" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
    {{ show }}
  </p>
  <p>
      {{ form.watching(class_="checkbox-inline") }} Watching
  </p>
  <p>
      {{ form.finished(class_="checkbox-inline",disabled="disabled") }} Finished
  </p>

  <button class="btn btn-sm btn-success" type="submit" name="btn" value="save">Save</button>
  <button class="btn btn-sm btn-danger" type="submit" name="btn" value="cancel">Cancel</button>
</form>

{% endblock %}

project/home/templates/index.html
{% extends "base.html" %}
{%  block content %}

        <h3>Welcome to Flask!</h3>
        <br>

        <!--<div class="jumbotron">-->
        <div class="panel panel-default">
            <div class="panel-heading">stuff</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-6">
                        <strong>Title</strong>
                    </div>
                    <div class="col-xs-2">
                        <strong>Watching</strong>
                    </div>
                    <div class="col-xs-2">
                        <strong>Finished</strong>
                    </div>
                </div>
                {% for show in shows %}
                    <div class="row">
                        <div class="col-xs-6">
                          {{ show.title }}
                        </div>
                        <div class="col-xs-2">
                            {% if show.watching %}
                           <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                            {% else %}
                            <span class="glyphicon glyphicon-unchecked" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                        <div class="col-xs-2">
                           {% if show.finished %}
                           <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                            {% else %}
                            <span class="glyphicon glyphicon-unchecked" aria-hidden="true"></span>
                            {% endif %}
                        </div>
                        <div class="col-xs-2">
                            <a href="{{ url_for('home.edit',show=show.title) }}">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </a>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        <!--</div>-->
            <p>Click <a href="/logout">here</a> to logout.</p>



{% endblock %}

project/home/templates/set_tvmaze_id.html
{% extends "base.html" %}

{% block content %}

<h1>Add series</h1>
<br>
    <span class="error">
      {% if form.selection.errors %}
        {% for error in form.selection.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
<form class="form-signin" role="form" method="post" action="">
  {{ form.csrf_token }}
    {{ form.title }}
    {% for subfield in form.selection %}
        <div class="row">
            <div class="col-xs-7">
                <div class="row">
                    <div class="radio">
                        {{ subfield }}
                        {{ subfield.label }} ({{ subfield.extra_data[0] }})
                    </div>
                </div>
                <div class="row">
                    {{ subfield.extra_data[1] }}
                </div>
            </div>
            <div class="col-xs-5">
                <img class="img-responsive" src={{ subfield.extra_data[2] }}>
            </div>
        </div>
    {% endfor %}

  <button class="btn btn-sm btn-success" type="submit">Select</button>
</form>

{% endblock %}

project/home/templates/welcome.html
{% extends "base.html" %}
{%  block content %}

      <h1>Welcome to Flask!</h1>
      <br>
      <p>Click <a href="/">here</a> to go home.</p>

{% endblock %}